/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class ConverterTest {
    @Test
    public void testToPounds(){
        Converter c = new Converter();
        assertEquals("1.250 lbs", c.toPounds(20));
    }
    @Test
    public void testToPoundsAndOunces(){
        Converter c = new Converter();
        assertEquals("1 lb and 4 oz", c.toPoundsAndOunces(20));
    }
}

